"""LoRA/QLoRA fine-tuning data preparation for LexReview.

:class:`DataPreparator` converts :class:`~src.lexreview.agent.models.AgentResponse`
objects (generated by the live agent) into JSONL training data compatible
with TRL's ``SFTTrainer``.

Only responses above a configurable confidence threshold are included to
keep training data quality high.

This module is **NOT wired to the API** — it is called offline or in Colab.

Typical usage::

    prep = DataPreparator()
    pairs = prep.build_from_responses(responses, questions)
    prep.save_jsonl(pairs, Path("data/sft_train.jsonl"))
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from src.lexreview.agent.models import AgentResponse
from src.utils.logger import get_logger

log = get_logger(__name__)


class DataPreparator:
    """Prepare SFT training data from LegalRAGAgent response objects.

    Args:
        min_confidence: Minimum agent confidence to include a sample (default 0.7).
        prompt_template: Template string with ``{question}`` and ``{context}`` placeholders.
            Defaults to a standard instruction-following format.

    Example::

        prep = DataPreparator(min_confidence=0.7)
        pairs = prep.build_from_responses(responses, questions)
        prep.save_jsonl(pairs, Path("data/train.jsonl"))
    """

    DEFAULT_PROMPT_TEMPLATE = (
        "### Instruction:\nYou are a legal document analysis assistant. "
        "Answer the following question based on the provided legal context.\n\n"
        "### Question:\n{question}\n\n"
        "### Context:\n{context}\n\n"
        "### Response:\n"
    )

    def __init__(
        self,
        min_confidence: float = 0.7,
        prompt_template: str | None = None,
    ) -> None:
        self._min_confidence = min_confidence
        self._template = prompt_template or self.DEFAULT_PROMPT_TEMPLATE

    def build_from_responses(
        self,
        responses: list[AgentResponse],
        questions: list[str],
    ) -> list[dict[str, str]]:
        """Convert agent responses to ``{"prompt": ..., "completion": ...}`` dicts.

        Args:
            responses: List of :class:`AgentResponse` from the live agent.
            questions: Corresponding question strings (same order as *responses*).

        Returns:
            List of JSONL-ready dicts.  Low-confidence responses are filtered out.
        """
        if len(responses) != len(questions):
            raise ValueError(
                f"responses ({len(responses)}) and questions "
                f"({len(questions)}) must have equal length."
            )

        records: list[dict[str, str]] = []
        skipped = 0

        for question, response in zip(questions, responses, strict=True):
            if response.confidence < self._min_confidence:
                skipped += 1
                continue

            context = "\n---\n".join(
                f"[{c.chunk_id}] {c.content}" for c in response.citations[:5]
            )
            prompt = self._template.format(
                question=question.strip(),
                context=context.strip(),
            )
            records.append({"prompt": prompt, "completion": response.answer.strip()})

        log.info(
            "DataPreparator: built SFT dataset",
            extra={
                "total": len(responses),
                "included": len(records),
                "skipped_low_confidence": skipped,
            },
        )
        return records

    def save_jsonl(
        self,
        records: list[dict[str, str]],
        path: Path,
    ) -> None:
        """Write *records* to a JSONL file at *path*.

        Args:
            records: List of ``{"prompt": ..., "completion": ...}`` dicts.
            path:    Output file path (created if not exists).
        """
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("w", encoding="utf-8") as f:
            for record in records:
                f.write(json.dumps(record, ensure_ascii=False) + "\n")
        log.info("DataPreparator: saved JSONL", extra={"path": str(path), "records": len(records)})

    def load_jsonl(self, path: Path) -> list[dict[str, Any]]:
        """Load records from a JSONL file.

        Args:
            path: Path to the JSONL file.

        Returns:
            List of dicts read from the file.
        """
        records: list[dict[str, Any]] = []
        with path.open("r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line:
                    records.append(json.loads(line))
        log.info("DataPreparator: loaded JSONL", extra={"path": str(path), "records": len(records)})
        return records
